### ISSUE TITLE
support revoke credentials

### ISSUE THREAD

**Issue by ktong** [GoogleCloudPlatform/google-auth-library-python#160]
I am switching from oauth2client to google-auth in my project. However, the revoke method in GoogleCrendetials does not exist in google-auth. Is there any plan to support it?

**Comment by jonparrott** [comment]
It seems that token revocation isn't part of the OAuth 2.0 RFC and it's implemented in oauthlib either. Which makes sense because not all credential types can be revoked. However, it is *really* easy to do this manually:

```python
import requests

requests.post(
    'https://accounts.google.com/o/oauth2/revoke',
    params={'token': credentials.token})
```

That said, we could consider adding it to this library but we'd need some more data to justify it. I'm going to close this issue, but if any one finds this and wants revocation built into the library please let us know. We can (and will) reconsider.

**Comment by mildsunrise** [comment]
Had the same problem. I understand it's not present in oauthlib, but this library is for google-specific auth... is there a reason this functionality should *not* be here? As you said it's easy to implement and shouldn't incur substantial maintenance cost, right?

It'd be essentially adding an instance method to `Flow` like:

~~~ python
def revoke(self, revoke_url="https://oauth2.googleapis.com/revoke", method="POST"):
    """Revokes the current token of the underlying OAuth 2.0 session.

    This method must only be called once the Authorization Flow has completed,
    otherwise there are no tokens to revoke. If successful, the token is cleared
    so that the OAuth 2.0 session becomes unauthorized again.
    """
    session = self.oauth2session
    token = session.token["access_token"]
    r = session.request(method=method, url=revoke_url, params=dict(token=token))
    session.token = {}
~~~
