### ISSUE TITLE
Minor observations for google-auth-httplib2 on PyPI

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/google-auth-library-python#167]
Hello,

I just want to share a few minor observations that I have for [google-auth-httplib2 on pypi](https://pypi.python.org/pypi/google-auth-httplib2/0.0.2). I hope these are helpful.

1. In the description for [google-auth-httplib2 on pypi](https://pypi.python.org/pypi/google-auth-httplib2/0.0.2), there is a duplicate `'and'` in the following line:

```
httplib has lots of problems such as lack of threadsafety and and insecure usage of TLS.
```

2. On pypi, `google-auth-httplib2-0.0.2.tar.gz` doesn't contain a LICENSE file. https://pypi.python.org/packages/43/20/c9adf8ee79ef9ab718945b317d3bad5ff36108bf7b1426e4d2f16e76d9d5/google-auth-httplib2-0.0.2.tar.gz#md5=5de90b67628b540cac13bb127ee65f9c

3. When I tried to import `google_auth_httplib2` I received `ImportError` because I didn't have `httplib2` installed in my test environment.

```
>>> import google_auth_httplib2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tony/miniconda2/lib/python2.7/site-packages/google_auth_httplib2.py", line 23, in <module>
    import httplib2
ImportError: No module named httplib2
```

**Comment by jonparrott** [comment]
Thanks @parthea! I'm traveling this week, but I'll try to get these addressed shortly.

**Comment by dhermes** [comment]
See https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2/pull/3.

The `LICENSE` file has been in [the MANIFEST][1] since the initial commit in that project and in the [last commit][1] before deletion in this project, the `LICENSE` file was in the MANIFEST.

[1]: https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2/blob/7cf7e5b891cbe31dcd1f40fdc2f8ea393571cd0a/MANIFEST.in
[2]: https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/0190660f79c4310987f405b3d8e5db4c5927665b/httplib2_transport/MANIFEST.in
