### ISSUE TITLE
When using cloud SDK google.auth.default returns token that results in odd 403 message

### ISSUE THREAD

**Issue by mr-mcox** [GoogleCloudPlatform/google-auth-library-python#182]
## Relevant portion of my script
```
scopes = ['https://www.googleapis.com/auth/analytics']
credentials, project = google.auth.default(scopes=scopes)
print(f'scopes: {credentials.scopes}')
session = AuthorizedSession(credentials)
url = 'https://analyticsreporting.googleapis.com/v4/reports:batchGet'
resp = session.post(url, json=body)
print(f'Response:\n{resp.json()}')

```

## Case 1
I run `gcloud auth application-default login --scopes=https://www.googleapis.com/auth/analytics` on the terminal, then run the above script.

My script prints the following:

```
scopes: None
Response:
{'error': {'code': 403, 'message': 'Google Analytics Reporting API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/analyticsreporting.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', 'status': 'PERMISSION_DENIED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/analyticsreporting.googleapis.com/overview?project=usable-auth-library'}]}]}}
```

What's odd here is the 403 message "Google Analytics Reporting API has not been used in project usable-auth-library before or it is disabled" which is different from the message in case 2

### Side note
When I use the token generated by the credentials from this case in the [OAuth2 Playground](https://developers.google.com/oauthplayground/) I receive the same error message

## Case 2
I run `gcloud auth application-default login` on the terminal

My script prints:

```
scopes: None
Response:
{'error': {'code': 403, 'message': 'Request had insufficient authentication scopes.', 'status': 'PERMISSION_DENIED'}}
```

## Case 3

When I run this with `GOOGLE_APPLICATION_CREDENTIALS` set with service account credentials, and run my script, there is no error in the response and
`scopes: ['https://www.googleapis.com/auth/analytics']`

## My questions
 
* Is this expected behavior of google-auth?
* If so, do you have any insights why the first and second cases would produce such different error messages?

**Comment by jonparrott** [comment]
This is due to the way that credentials are issued to the Google Cloud SDK. Running `gcloud auth application-default login` grants your user credentials (the *principal* is *you*) to the Cloud SDK project (the credentials project is the *Cloud SDK*).

When `google-auth` uses these credentials to access APIs, the API backend looks up the project that was issued these credentials to perform quota and billing (for resourceless APIs). In the case of Cloud SDK credentials, this project is the *Cloud SDK*'s project, not your project. The Cloud SDK project does not have all APIs enabled and has limited quota that is shared across all Cloud SDK users.

Because of this, you should either use a service account or obtain user credentials using your own project (see [here](http://google-auth.readthedocs.io/en/latest/user-guide.html#user-credentials)).

**Comment by mr-mcox** [comment]
@jonparrott Thank you for the quick and thoughtful response!
