### ISSUE TITLE
Example for Server to Server Applications

### ISSUE THREAD

**Issue by tarasinf** [GoogleCloudPlatform/google-auth-library-python#191]
Can you provide some workable examples of using for Server to Server Applications? I tried it in a few [ways](https://stackoverflow.com/questions/45606906/cant-insert-into-google-fusion-tables-by-two-legged-oauth-in-python)

**Comment by jonparrott** [comment]
This library presently only does server to server auth, so all of the samples here use that flow. I'm not sure why it's not working for fusion tables, but I'm unfamiliar with the auth needs of that service - it may be a case where you must authenticate as a user in order to use the API.

(I'm closing this as it seems this library is working as intended, but feel free to comment)
