### ISSUE TITLE
Could not automatically determine credentials #Ubuntu Flask Apache

### ISSUE THREAD

**Issue by udayrddy** [GoogleCloudPlatform/google-auth-library-python#209]
I'm using python3.5, everything is working fine on Windows, but when I tried to deploy the application on Ubuntu 16. the application is throwing the error
**google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials**

Application is working fine when I tried to execute through command line. using 
`python application_name.py`

The problem in when I'm trying to interact the application through Flask in Apache - WSGI. 

tried below, are of no help:
google auth default
export GOOGLE_APPLICATION_CREDENTAILS=

```

>>> import google.auth
>>> credentials, project_id = google.auth.default()
>>> credentials
<google.oauth2.service_account.Credentials object at 0x7fc23f3d52e8>
>>> project_id
'elided'

```

I am able to print the access token in the virtual environment created for the flask application

**Comment by udayrddy** [comment]
>>> import google.auth
>>> credentials, project_id = google.auth.default()
>>> credentials
<google.oauth2.service_account.Credentials object at 0x7fc23f3d52e8>
>>> project_id
'aqueous-freedom-178413'

**Comment by jonparrott** [comment]
@udayrddy to make sure I understand - this works okay in Ubuntu if you manually run the Python application, but doesn't work when running it as a web app under apache?

**Comment by udayrddy** [comment]
@jonparrott Yes, you are correct. My application uses Google vision which extracts text from an image. Application is working fine till the point it hits the function which uses Google Vision.

The same function is working fine if execute it as a separate PROGRAM through command line

**Comment by jonparrott** [comment]
How are you running apache / wsgi? It's likely you need to modify whatever configuration is there to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable for your application.

**Comment by udayrddy** [comment]
I believe export `GOOGLE_APPLICATION_CREDENTIALS` sets up the environment. Isn't it ? Also, I added it to /.profile of my ubuntu instance. Am I missing anything ?

**Comment by jonparrott** [comment]
Most of the time apache / nginx / etc servers run under their own user accounts, so setting your own ~/.profile doesn't set the environment for those programs. If you can tell me more about how you're running your application's web and wsgi server I might be able to help you get it set up.

**Comment by udayrddy** [comment]
I've created a **virtualenv** with python3 in it and pushed my entire repository into it. 
Wrapped the application.py under `FLASK_APP` and run in the virtualenv
Routed the application to a aws ec2 (DNS) url

**Comment by jonparrott** [comment]
That's helpful, but still not the information I need to help.

For example, you can usually set env vars for Apache in the config file as noted [here](https://stackoverflow.com/questions/10902433/setting-environment-variables-for-accessing-in-php). You can set it for mod_wsgi specifically as noted [here](http://drumcoder.co.uk/blog/2010/nov/12/apache-environment-variables-and-mod_wsgi/). 

If you're using nginx (or apache in reverse proxy mode), you'll set the environment variables using whatever supervisor you're using to run your actual WSGI server. For supervisor, see [here](http://supervisord.org/configuration.html#environment-variables). For systemd see [here](https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html).

Since this doesn't appear to be an issue with this library directly, I'm going to go ahead and close this issue. Please feel free to continue to comment, but note that it's difficult for me to provide full support for a specific hosting platform and configuration. In general, you need to ensure the environment variable is set. If you verify that the variable is set in your application's `os.environ` but `google-auth` is still not loading your credentials, then we can re-open this bug.

**Comment by udayrddy** [comment]
@jonparrott  Thanks a ton, for the pointer, it helped me to change my approach of resolving the issue and I got it. Thanks again for the swift response.

**Comment by jonparrott** [comment]
No problem! Happy to help.
