### ISSUE TITLE
ImportError: cannot import name 'DependencyWarning'

### ISSUE THREAD

**Issue by iczubieta** [GoogleCloudPlatform/google-auth-library-python#237]
I'm having the same issue as what was posted in this [StackOverflow post](https://stackoverflow.com/questions/48346999/firebase-dynamic-links-python-issue), can anyone help me on how this issue can be solved?

**Comment by jonparrott** [comment]
The problem here is that requests is not properly installed in your environment. Because your stacktrace contains `dist-packages` it appears you're using os packages. I would *highly* recommend that you create and use a virtualenv for development, as os packages are meant for the os, not for development.

See https://cloud.google.com/python/setup for guidance on how to setup a Python development environment, including virtualenv usage.

(I'm going to go ahead and close this issue, but feel free to comment if you have any more questions.)
