### ISSUE TITLE
AttributeError: module 'google.auth.transport' has no attribute 'requests'

### ISSUE THREAD

**Issue by hiranya911** [GoogleCloudPlatform/google-auth-library-python#241]
I'm seeing the following error in some environments:

Python 3.6.1 on Mac (With or without virtualenv)
```
>>> from google.auth import transport
>>> transport.requests.AuthorizedSession(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.auth.transport' has no attribute 'requests'
```

It sometimes work (even on the same machine).

**Comment by jonparrott** [comment]
Because `google.auth.transport` is a *package* and not a *module*, you have to explicitly import the *module* (think of it like a tree - you have to import the leaf). 

So, this should all work:

```python
from google.auth.transport import requests
import google.auth.transport.requests
```

But these will not:

```python
from google.auth import transport
transport.request  # AttributeError
import google.auth.transport
google.auth.transport.request  # AttributeError
```

However, those *will* work after you import the `google.auth.transport.requests` module.

Confusing, I know. See https://docs.python.org/3/tutorial/modules.html#packages and https://docs.python.org/3/reference/import.html for more details.

**Comment by hiranya911** [comment]
Very interesting. We've had the following 2 lines in Admin SDK for as long as I could remember. And it seems to work fine too:

```
from google.auth import transport

...
self._session = transport.requests.AuthorizedSession(credential)
```

But on its own those 2 lines do not work. I'll update our code to be on the safe side.
