### ISSUE TITLE
Way to disable _CLOUD_SDK_CREDENTIALS_WARNING

### ISSUE THREAD

**Issue by ryanchapman** [GoogleCloudPlatform/google-auth-library-python#271]
Is there a way to disable the warning `_CLOUD_SDK_CREDENTIALS_WARNING`, maybe by setting an environment variable?  We have an application where we want users to use their gcloud user credentials since it is run on their local machine.  If we ran the app as a service on a server, then a service account would make more sense.

> UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.

**Comment by theacodes** [comment]
> We have an application where we want users to use their gcloud user credentials since it is run on their local machine.

You should move away from that as quickly as possible and either do the OAuth 2.0 flow yourself or recommend your users create service accounts. At some later date, we will formally deprecate this authentication mechanism (though it may be a very long time before we completely remove it).

> Is there a way to disable the warning

You can use the standard library filterwarnings. https://docs.python.org/3/library/warnings.html#warnings.filterwarnings

**Comment by ryanchapman** [comment]
Why deprecate user credentials and require service accounts?  What about applications where end-users run an app on their local machine?  Today, it's easy for them to set up authentication with `gcloud auth login`.  It's not as easy for users to create a service account and then keep up with that credential file.

**Comment by theacodes** [comment]
We're not deprecating end user credentials, just (currently discouraging, but considering deprecation) one way of obtaining those. The trouble with the Cloud SDK is that all credentials that are issued from it share the same client ID, and thus, quota. This doesn't work well for a significant portion of our APIs and often leads to users being confused and frustrated when things don't work.

**Comment by matschaffer** [comment]
Incase anyone else is looking for the warning suppression, mentioned in https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/271#issuecomment-395838430 this seems to do the trick:

```
import warnings
warnings.filterwarnings("ignore", "Your application has authenticated using end user credentials")
```

**Comment by erlichmen** [comment]
@theacodes  I think there is a scenario your not taking into account: we (and many other) provide tools that allow the user to use his own resources (gcs bucket, vm, etc) and the fact that he already has gcloud setup the authentication for hims is very convenient. The google auth lib (python in our case) goes into the application default authentication file and nothing needs to be setup for auth again. 
Moreover this is how the boto lib works in AWS, it will be a pain that each tool will need to be setup again and request the same permission as gcloud.

**Comment by matschaffer** [comment]
@erlichmen You can get similar behavior to aws cli by having a convention around users creating service accounts and keeping the key file in a known location. That being said we haven't run into any trouble with human-driven workloads anyway (utility scripts, builds, etc) from suppressing the warning and using the Cloud SDK oauth creds.

**Comment by erlichmen** [comment]
@matschaffer I really don't want to tell me client to generate a key with permissions equal to gcloud.

**Comment by ryanchapman** [comment]
@matschaffer what if the end user needs access to a protected bucket?  In that case, they have to generate a service account, then ask the administrator of the bucket to give their service account access to the bucket.  Or maybe I'm missing something here...

**Comment by matschaffer** [comment]
@ryanchapman sounds like you understand it correctly. There's some extra hassle involved, but it's an option at least. We just suppress the warming and use cloud sdk, though.

**Comment by ryanchapman** [comment]
I've been thinking about this and it seems that the missing piece here is the link to a user account.  If Google could come up with a way for a user authenticated via their Google Apps account to generate a service account (via a `gcloud` command or API call that could be automated), then we could still grant Google Apps users and groups access to the bucket (or whatever resource).  For me, the benefit of using Google Apps accounts is that when an employee leaves the company, IT takes care of disabling accounts and the Cloud admins don't have to do anything.  

AWS IAM works similarly: it has the ability to create users and then multiple access keys can be created that are associated with a user.

**Comment by max-sixty** [comment]
I was previously commenting on https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/266, but this seems to be the more active thread.

The only reason I can see (but tell me if I'm missing something) for this is "The trouble with the Cloud SDK is that all credentials that are issued from it share the same client ID, and thus, share quota."

Could you help us understand what this means? I've never seen a quota error, for example.

**Comment by thejens** [comment]
To add a use case to this thread, the ability to easily auth as oneself (default credentials from gcloud) is great when working with tools like locally hosted Jupyter notebooks. 

For data protection/access management we really prefer the ability to grant access to users instead of their service-accounts - and for the same reason it makes no sense to share service accounts between end users. Also if all users need their own service account, I think we'd hit the limit of how many can be created in the same project (100?).

**Comment by bmccutchon** [comment]
If you're trying to build a tool that performs actions on behalf of a user (e.g. a CLI tool), you can use `gcloud config config-helper` to get their user credentials.

**Comment by joaqo** [comment]
@theacodes I am too currently implementing a tool that uses a user's gcloud account on their behalf. We are trying to make it as easy as possible to use, so we don't want to make the user create a service account. What is the recommended way of doing this that wont get deprecated?

**Comment by bmccutchon** [comment]
@joaqo You should check out `gcloud config config-helper`; that's what it's built for. See, for example, [how `docker-credential-gcr` (an official Google project!) uses it](https://github.com/GoogleCloudPlatform/docker-credential-gcr/blob/e84196148f42a4b3c37a8f517ffb6aeb2d2f572e/credhelper/helper.go#L215).

**Comment by pkaramol** [comment]
@bmccutchon your suggestion is therefore to run the above command, get the temporary token and perform all subsequent authentications using this token? I guess this needs some extra boilerplate code for a) checking when/whether the token has expired b) re-issuing it.

Forgetting to issue it might end up in auth failures, while proactively issuing it upon each request will create extra overhead for the app.

Any recommended patterns / strategies about that?

**Comment by sayap** [comment]
@bmccutchon I think you should include `--account <email>` when shelling out to `gcloud config config-helper`, otherwise we just go from one implicit default (the "application default credential" or ADC) to another implicit default (the currently active account for gcloud).

Also, both the shelling out and the `--force-auth-refresh` flag seem a little excessive, while at the same time we are still using "google cloud sdk" as the oauth client, just with a different set of credential.

#266 specifically checks for client id "764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com", or `CLOUD_SDK_CLIENT_ID` as per google/auth/_cloud_sdk.py, used by ADC.

With `gcloud config config-helper`, we will use client id "32555940559.apps.googleusercontent.com" instead, or `CLOUDSDK_CLIENT_ID` as per googlecloudsdk/core/config.py.

To get around the nagging from #266, perhaps it is simpler to use `~/.config/gcloud/legacy_credentials/<email>/adc.json` instead, without having to shell out to gcloud. For example, with ansible, we can set `auth_kind: application`, and then set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to the adc.json file for the appropriate email account.

Anyway, someone from Google really needs to explain the "share quota" bits. If it is just some oauth client quota given to "google cloud sdk", there should be no problem to just give it unlimited quota right? The actual API call can still be tied to an email and a project, so billing can still be done correctly right? What's the missing link here, such that `gcloud auth application-default set-quota-project` is required?

**Comment by loeffel-io** [comment]
> Incase anyone else is looking for the warning suppression mentioned in [#271 (comment)](https://github.com/googleapis/google-auth-library-python/issues/271#issuecomment-395838430) this seems to do the trick:
> 
> ```
> import warnings
> warnings.filterwarnings("ignore", "Your application has authenticated using end user credentials")
> ```

how i can use this in a bash script? (no python background)

**Comment by thenger** [comment]
Is this issue "closed" as in "won't fix" or it is just waiting ?
